### ISSUE TITLE
🔨 [vimure v0.1-R] Implement VimureModel

### ISSUE THREAD

**Issue by gabiborges1** [latentnetworks/vimure#25]
Full [(Python version)](https://github.com/latentnetworks/vimure/blob/main/src/python/vimure/model.py) for reference.

## Requirements

- [x] Make sure #24 is complete before taking on this task
- [x] Make sure #23 is complete before taking on this task

## Tasks

Functions that need to be implemented in R:
- [ ] [vm.model.py#VimureModel::initialize_priors](https://github.com/latentnetworks/vimure/blob/main/src/python/vimure/model.py#L498)
- [ ] [vm.model.py#VimureModel::update_cache](https://github.com/latentnetworks/vimure/blob/main/src/python/vimure/model.py#L582)
- [ ] [vm.model.py#VimureModel::update_gamma](https://github.com/latentnetworks/vimure/blob/main/src/python/vimure/model.py#L614)
- [ ]  [vm.model.py#VimureModel::update_phi](https://github.com/latentnetworks/vimure/blob/main/src/python/vimure/model.py#L639)
- [ ]  [vm.model.py#VimureModel::update_rho](https://github.com/latentnetworks/vimure/blob/main/src/python/vimure/model.py#L669)
- [ ]  [vm.model.py#VimureModel::update_nu](https://github.com/latentnetworks/vimure/blob/main/src/python/vimure/model.py#L713)
