### ISSUE TITLE
Ensure CONTRIBUTING.MD is up-to-date

### ISSUE THREAD

**Issue by jonjoncardoso** [latentnetworks/vimure#63]
## Tasks

- [x] Test the development setup on a clean Windows install
- [x] Update CONTRIBUTING.MD as needed
- [x] Test codebase with `pytest`

**Comment by jonjoncardoso** [comment]
This is now solved with 68d6e1e
