### ISSUE TITLE
Add 💻 Tutorial 01: How to prepare your data for VIMuRe

### ISSUE THREAD

**Issue by jonjoncardoso** [latentnetworks/vimure#68]
**OBJECTIVE:** Illustrate how one would go about preparing their data to a format that would work well when interacting with VIMuRe

# Tasks

I will be using the Karnataka data as an example.

- [x] Download the original data
- [x] Cleaning the original data
- [x] Restructuring it to the format we need
- [x] Explain why we need the data that way
